### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by claudebarde** [persianturtle/rescript-react-boilerplate#29]
When installing the node modules the first time with `npm install`, I got the following error:
```
code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/colors/-/colors-1.4.1.tgz - Not found
npm ERR! 404 
npm ERR! 404  'colors@https://registry.npmjs.org/colors/-/colors-1.4.1.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git URL.
```
The error went away after deleting the `package-lock.json` file and rebuilding it.

**Comment by persianturtle** [comment]
Thank you for the issue. I'm resolving this issue now.

Context:

This is because `colors@1.4.1` was a malicious upgrade ([source](https://snyk.io/blog/open-source-npm-packages-colors-faker/)). I'll resolve the dependency to `1.4.0`.

**Comment by claudebarde** [comment]
Thanks a lot for the repo, it is extremely useful for Rescript beginners like myself!
